class Utils:
    FIRST_LINE = 0
    SECOND_LINE = 1
    THIRD_LINE = 2
    FOURTH_LINE = 3
    TIMESTAMP_LENGTH = 8
    AUTH_SERVER_PORT = 1234
    DEFAULT_MSG_SERVER_PORT = 1235
    AUTH_SERVER_IP = "127.0.0.1"
    MAX_BYTE_VALUE = 255
    MIN_BYTE_VALUE = 0
    ME_INFO_FILE = "me.info"
    SERVER_INFO_FILE = "srv.info"
    MSG_SERVER_INFO_FILE = "msg.info"
    MINIMUM_LINES_ME_INFO = 2
    ENCRYPTED_DATA = 48
    DECRYPTED_DATA = 32
    DECRYPTED_NONCE = 8
